export const gql = (type: string) => `


{
    __schema{
        types{
            name
            kind
        }
        queryType{
            name
        }
        mutationType{
            name
        }
        subscriptionType{
            name
        }
    }
    __type(name:"${type}"){
        name
        description
        kind
        enumValues{
            name
            description
        }
        possibleTypes{
            name
        }
        inputFields{
            type{
                name
                kind
                ofType{
                    name
                    kind
                    enumValues{
                        name
                    }
                    description
                    ofType{
                        name
                        kind
                        ofType{
                            name
                            kind
                        }
                    }
                }
                enumValues{
                    name
                }
            }
            name
            description
            __typename
        }
        fields{
            type{
                name
                kind
                ofType{
                    name
                    kind
                    enumValues{
                        name
                    }
                    description
                    ofType{
                        name
                        kind
                        ofType{
                            name
                            kind
                        }
                    }
                }
                enumValues{
                    name
                }
            }
            args{
                type{
                    name
                    kind
                    ofType{
                        name
                        kind
                        ofType{
                            name
                            kind
                            ofType{
                                name
                                kind
                            }
                        }
                    }
                }
                name
            }
            name
            description
            __typename
        }
    }
}



`;
